apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  resources:
    requests:
      storage: 200Mi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
#pa55w0rd
#kubectl create secret generic mssql --from-literal=SA_PASSWORD="pa55w0rd!"